# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pet.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import datetime_pb2 as datetime__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tpet.proto\x12\x06pet.v1\x1a\x0e\x64\x61tetime.proto\"q\n\x03Pet\x12!\n\x08pet_type\x18\x01 \x01(\x0e\x32\x0f.pet.v1.PetType\x12\x0e\n\x06pet_id\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12)\n\ncreated_at\x18\x04 \x01(\x0b\x32\x15.google.type.DateTime\"\x1f\n\rGetPetRequest\x12\x0e\n\x06pet_id\x18\x01 \x01(\t\"*\n\x0eGetPetResponse\x12\x18\n\x03pet\x18\x01 \x01(\x0b\x32\x0b.pet.v1.Pet\"@\n\rPutPetRequest\x12!\n\x08pet_type\x18\x01 \x01(\x0e\x32\x0f.pet.v1.PetType\x12\x0c\n\x04name\x18\x02 \x01(\t\"*\n\x0ePutPetResponse\x12\x18\n\x03pet\x18\x01 \x01(\x0b\x32\x0b.pet.v1.Pet\"\"\n\x10\x44\x65letePetRequest\x12\x0e\n\x06pet_id\x18\x01 \x01(\t\"\x13\n\x11\x44\x65letePetResponse*q\n\x07PetType\x12\x18\n\x14PET_TYPE_UNSPECIFIED\x10\x00\x12\x10\n\x0cPET_TYPE_CAT\x10\x01\x12\x10\n\x0cPET_TYPE_DOG\x10\x02\x12\x12\n\x0ePET_TYPE_SNAKE\x10\x03\x12\x14\n\x10PET_TYPE_HAMSTER\x10\x04\x32\xcb\x01\n\x0fPetStoreService\x12\x39\n\x06GetPet\x12\x15.pet.v1.GetPetRequest\x1a\x16.pet.v1.GetPetResponse\"\x00\x12\x39\n\x06PutPet\x12\x15.pet.v1.PutPetRequest\x1a\x16.pet.v1.PutPetResponse\"\x00\x12\x42\n\tDeletePet\x12\x18.pet.v1.DeletePetRequest\x1a\x19.pet.v1.DeletePetResponse\"\x00\x42\x08Z\x06pet/v1b\x06proto3')

_PETTYPE = DESCRIPTOR.enum_types_by_name['PetType']
PetType = enum_type_wrapper.EnumTypeWrapper(_PETTYPE)
PET_TYPE_UNSPECIFIED = 0
PET_TYPE_CAT = 1
PET_TYPE_DOG = 2
PET_TYPE_SNAKE = 3
PET_TYPE_HAMSTER = 4


_PET = DESCRIPTOR.message_types_by_name['Pet']
_GETPETREQUEST = DESCRIPTOR.message_types_by_name['GetPetRequest']
_GETPETRESPONSE = DESCRIPTOR.message_types_by_name['GetPetResponse']
_PUTPETREQUEST = DESCRIPTOR.message_types_by_name['PutPetRequest']
_PUTPETRESPONSE = DESCRIPTOR.message_types_by_name['PutPetResponse']
_DELETEPETREQUEST = DESCRIPTOR.message_types_by_name['DeletePetRequest']
_DELETEPETRESPONSE = DESCRIPTOR.message_types_by_name['DeletePetResponse']
Pet = _reflection.GeneratedProtocolMessageType('Pet', (_message.Message,), {
  'DESCRIPTOR' : _PET,
  '__module__' : 'pet_pb2'
  # @@protoc_insertion_point(class_scope:pet.v1.Pet)
  })
_sym_db.RegisterMessage(Pet)

GetPetRequest = _reflection.GeneratedProtocolMessageType('GetPetRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETPETREQUEST,
  '__module__' : 'pet_pb2'
  # @@protoc_insertion_point(class_scope:pet.v1.GetPetRequest)
  })
_sym_db.RegisterMessage(GetPetRequest)

GetPetResponse = _reflection.GeneratedProtocolMessageType('GetPetResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETPETRESPONSE,
  '__module__' : 'pet_pb2'
  # @@protoc_insertion_point(class_scope:pet.v1.GetPetResponse)
  })
_sym_db.RegisterMessage(GetPetResponse)

PutPetRequest = _reflection.GeneratedProtocolMessageType('PutPetRequest', (_message.Message,), {
  'DESCRIPTOR' : _PUTPETREQUEST,
  '__module__' : 'pet_pb2'
  # @@protoc_insertion_point(class_scope:pet.v1.PutPetRequest)
  })
_sym_db.RegisterMessage(PutPetRequest)

PutPetResponse = _reflection.GeneratedProtocolMessageType('PutPetResponse', (_message.Message,), {
  'DESCRIPTOR' : _PUTPETRESPONSE,
  '__module__' : 'pet_pb2'
  # @@protoc_insertion_point(class_scope:pet.v1.PutPetResponse)
  })
_sym_db.RegisterMessage(PutPetResponse)

DeletePetRequest = _reflection.GeneratedProtocolMessageType('DeletePetRequest', (_message.Message,), {
  'DESCRIPTOR' : _DELETEPETREQUEST,
  '__module__' : 'pet_pb2'
  # @@protoc_insertion_point(class_scope:pet.v1.DeletePetRequest)
  })
_sym_db.RegisterMessage(DeletePetRequest)

DeletePetResponse = _reflection.GeneratedProtocolMessageType('DeletePetResponse', (_message.Message,), {
  'DESCRIPTOR' : _DELETEPETRESPONSE,
  '__module__' : 'pet_pb2'
  # @@protoc_insertion_point(class_scope:pet.v1.DeletePetResponse)
  })
_sym_db.RegisterMessage(DeletePetResponse)

_PETSTORESERVICE = DESCRIPTOR.services_by_name['PetStoreService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\006pet/v1'
  _PETTYPE._serialized_start=396
  _PETTYPE._serialized_end=509
  _PET._serialized_start=37
  _PET._serialized_end=150
  _GETPETREQUEST._serialized_start=152
  _GETPETREQUEST._serialized_end=183
  _GETPETRESPONSE._serialized_start=185
  _GETPETRESPONSE._serialized_end=227
  _PUTPETREQUEST._serialized_start=229
  _PUTPETREQUEST._serialized_end=293
  _PUTPETRESPONSE._serialized_start=295
  _PUTPETRESPONSE._serialized_end=337
  _DELETEPETREQUEST._serialized_start=339
  _DELETEPETREQUEST._serialized_end=373
  _DELETEPETRESPONSE._serialized_start=375
  _DELETEPETRESPONSE._serialized_end=394
  _PETSTORESERVICE._serialized_start=512
  _PETSTORESERVICE._serialized_end=715
# @@protoc_insertion_point(module_scope)
